premiumModels:
  - openai/gpt-4
  - anthropic/claude-3-sonnet

providers:
  openai:
    apiKey: ${GITHUB_API_KEY}
    baseUrl: https://models.inference.ai.azure.com/
    models:
      - gpt-4: openai/gpt-4
      - gpt-3.5-turbo: openai/gpt-3.5-turbo
  anthropic:
    apiKey: YOUR_ANTHROPIC_API_KEY
    baseUrl: https://api.anthropic.com/v1
    models:
      - claude-3-sonnet: anthropic/claude-3-sonnet 